Linear Regression

1. X-y split (y is the target variable, in this case, "total claim amount")
2. Train-test split.
3. Standardize the data (after the data split!).
4. Apply linear regression.
4. Model Interpretation.


In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PowerTransformer, StandardScaler, MinMaxScaler, OrdinalEncoder

In [2]:
data = pd.read_csv('marketing_customer_analysis_clean.csv')

In [3]:
data

unnamed:_0 customer       state  customer_lifetime_value response  \
0               0  DK49336     Arizona              4809.216960       No   
1               1  KX64629  California              2228.525238       No   
2               2  LZ68649  Washington             14947.917300       No   
3               3  XL78013      Oregon             22332.439460      Yes   
4               4  QA50777      Oregon              9025.067525       No   
...           ...      ...         ...                      ...      ...   
10905       10905  FE99816      Nevada             15563.369440       No   
10906       10906  KX53892      Oregon              5259.444853       No   
10907       10907  TL39050     Arizona             23893.304100       No   
10908       10908  WA60547  California             11971.977650       No   
10909       10909  IV32877  California              6857.519928       No   

       coverage education effective_to_date employmentstatus gender  ...  \
0         Basic   College        2011-02-18         Employed      M  ...   
1         Basic   College        2011-01-18       Unemployed      F  ...   
2         Basic  Bachelor        2011-02-10         Employed      M  ...   
3      Extended   College        2011-01-11         Employed      M  ...   
4       Premium  Bachelor        2011-01-17    Medical Leave      F  ...   
...         ...       ...               ...              ...    ...  ...   
10905   Premium  Bachelor        2011-01-19       Unemployed      F  ...   
10906     Basic   College        2011-01-06         Employed      F  ...   
10907  Extended  Bachelor        2011-02-06         Employed      F  ...   
10908   Premium   College        2011-02-13         Employed      F  ...   
10909     Basic  Bachelor        2011-01-08       Unemployed      M  ...   

       number_of_policies     policy_type        policy  renew_offer_type  \
0                       9  Corporate Auto  Corporate L3            Offer3   
1                       1   Personal Auto   Personal L3            Offer4   
2                       2   Personal Auto   Personal L3            Offer3   
3                       2  Corporate Auto  Corporate L3            Offer2   
4                       7   Personal Auto   Personal L2            Offer1   
...                   ...             ...           ...               ...   
10905                   7   Personal Auto   Personal L1            Offer3   
10906                   6   Personal Auto   Personal L3            Offer2   
10907                   2  Corporate Auto  Corporate L3            Offer1   
10908                   6   Personal Auto   Personal L1            Offer1   
10909                   3   Personal Auto   Personal L1            Offer4   

       sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
0              Agent          292.800000  Four-Door Car       Medsize   
1        Call Center          744.924331  Four-Door Car       Medsize   
2        Call Center          480.000000            SUV       Medsize   
3             Branch          484.013411  Four-Door Car       Medsize   
4             Branch          707.925645  Four-Door Car       Medsize   
...              ...                 ...            ...           ...   
10905            Web         1214.400000     Luxury Car       Medsize   
10906         Branch          273.018929  Four-Door Car       Medsize   
10907            Web          381.306996     Luxury SUV       Medsize   
10908         Branch          618.288849            SUV       Medsize   
10909            Web         1021.719397            SUV       Medsize   

      vehicle_type month  
0                A     2  
1                A     1  
2                A     2  
3                A     1  
4                A     1  
...            ...   ...  
10905            A     1  
10906            A     1  
10907            A     2  
10908            A     2  
10909            A     1  

[10910 rows x 27 columns]

In [4]:
data_numericals = data.select_dtypes(include="number")

In [5]:
X = data_numericals.drop("total_claim_amount", axis=1)

In [6]:
data_numericals

unnamed:_0  customer_lifetime_value  income  monthly_premium_auto  \
0               0              4809.216960   48029                    61   
1               1              2228.525238       0                    64   
2               2             14947.917300   22139                   100   
3               3             22332.439460   49078                    97   
4               4              9025.067525   23675                   117   
...           ...                      ...     ...                   ...   
10905       10905             15563.369440       0                   253   
10906       10906              5259.444853   61146                    65   
10907       10907             23893.304100   39837                   201   
10908       10908             11971.977650   64195                   158   
10909       10909              6857.519928       0                   101   

       months_since_last_claim  months_since_policy_inception  \
0                     7.000000                             52   
1                     3.000000                             26   
2                    34.000000                             31   
3                    10.000000                              3   
4                    15.149071                             31   
...                        ...                            ...   
10905                15.149071                             40   
10906                 7.000000                             68   
10907                11.000000                             63   
10908                 0.000000                             27   
10909                31.000000                              1   

       number_of_open_complaints  number_of_policies  total_claim_amount  \
0                       0.000000                   9          292.800000   
1                       0.000000                   1          744.924331   
2                       0.000000                   2          480.000000   
3                       0.000000                   2          484.013411   
4                       0.384256                   7          707.925645   
...                          ...                 ...                 ...   
10905                   0.384256                   7         1214.400000   
10906                   0.000000                   6          273.018929   
10907                   0.000000                   2          381.306996   
10908                   4.000000                   6          618.288849   
10909                   0.000000                   3         1021.719397   

       month  
0          2  
1          1  
2          2  
3          1  
4          1  
...      ...  
10905      1  
10906      1  
10907      2  
10908      2  
10909      1  

[10910 rows x 10 columns]

In [7]:
X

unnamed:_0  customer_lifetime_value  income  monthly_premium_auto  \
0               0              4809.216960   48029                    61   
1               1              2228.525238       0                    64   
2               2             14947.917300   22139                   100   
3               3             22332.439460   49078                    97   
4               4              9025.067525   23675                   117   
...           ...                      ...     ...                   ...   
10905       10905             15563.369440       0                   253   
10906       10906              5259.444853   61146                    65   
10907       10907             23893.304100   39837                   201   
10908       10908             11971.977650   64195                   158   
10909       10909              6857.519928       0                   101   

       months_since_last_claim  months_since_policy_inception  \
0                     7.000000                             52   
1                     3.000000                             26   
2                    34.000000                             31   
3                    10.000000                              3   
4                    15.149071                             31   
...                        ...                            ...   
10905                15.149071                             40   
10906                 7.000000                             68   
10907                11.000000                             63   
10908                 0.000000                             27   
10909                31.000000                              1   

       number_of_open_complaints  number_of_policies  month  
0                       0.000000                   9      2  
1                       0.000000                   1      1  
2                       0.000000                   2      2  
3                       0.000000                   2      1  
4                       0.384256                   7      1  
...                          ...                 ...    ...  
10905                   0.384256                   7      1  
10906                   0.000000                   6      1  
10907                   0.000000                   2      2  
10908                   4.000000                   6      2  
10909                   0.000000                   3      1  

[10910 rows x 9 columns]

In [8]:
y = data[['total_claim_amount']]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 100)

In [11]:
#Standardize the data (after the data split!)

In [12]:
scaler = StandardScaler()

In [13]:
scaler = scaler.fit(X_train)

In [14]:
scaled_data_X_train = scaler.transform(X_train)

In [15]:
scaled_data_X_train

array([[ 1.05625245e+00, -2.98648890e-01,  3.52458281e-01, ...,
         7.75180701e-03,  4.15700463e-01, -9.40879087e-01],
       [-9.26858346e-01, -3.92856956e-01, -1.23962932e+00, ...,
        -4.29233533e-01, -5.08688771e-04, -9.40879087e-01],
       [ 1.01608657e+00, -8.21583003e-01, -5.04791755e-01, ...,
        -4.29233533e-01, -8.32926993e-01, -9.40879087e-01],
       ...,
       [ 8.28964554e-01, -4.55120589e-01,  9.85263473e-01, ...,
        -4.29233533e-01,  2.49674622e+00,  1.06283582e+00],
       [ 4.77353686e-01,  1.95351558e+00, -1.23962932e+00, ...,
        -4.29233533e-01, -4.16717841e-01, -9.40879087e-01],
       [ 6.42188864e-02, -5.01884344e-01, -1.23962932e+00, ...,
        -4.29233533e-01,  2.49674622e+00,  1.06283582e+00]])

In [16]:
scaled_data_X_test = scaler.transform(X_test)
scaled_data_X_test

array([[-1.33521149e+00, -7.60433435e-01, -3.56162176e-01, ...,
        -4.29233533e-01, -8.32926993e-01,  1.06283582e+00],
       [-1.74037668e-04, -7.90734698e-01, -5.60556703e-01, ...,
         7.07990660e-01, -8.32926993e-01,  1.06283582e+00],
       [ 1.50381515e+00, -7.39859968e-02, -1.23962932e+00, ...,
        -4.29233533e-01,  2.08053707e+00, -9.40879087e-01],
       ...,
       [-6.32946088e-01, -1.81433873e-01, -1.23962932e+00, ...,
        -4.29233533e-01,  8.31909616e-01,  1.06283582e+00],
       [ 1.21213433e+00, -5.93347245e-01,  1.81207528e+00, ...,
        -4.29233533e-01, -8.32926993e-01,  1.06283582e+00],
       [ 1.59721677e+00,  5.09205519e-02,  1.18606345e+00, ...,
        -4.29233533e-01,  2.49674622e+00,  1.06283582e+00]])

In [17]:
# make a dataframe out of scaled_data_X_test 
# scaled_data_X_test = pd.DataFrame(scaled_data_X_test, columns = X_train.columns)

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lm = LinearRegression()

In [20]:
model = lm.fit(scaled_data_X_train, y_train) #here we are creating our model 

In [21]:
model.coef_

array([[   0.64699307,   -4.01850007, -101.715123  ,  181.59872819,
          -1.35454955,   -4.97933472,   -2.41471714,    0.42409511,
          -0.85733405]])

In [22]:
model.intercept_

array([434.06224734])

In [23]:
# here i am testing the data to see if it works

In [24]:
y_pred = model.predict(scaled_data_X_test) #we let the model predict outcomes for the Data

In [25]:
# we see that the numbers are close to zero so the data is okay

In [26]:
y_pred

array([[358.14384661],
       [368.5184409 ],
       [635.38027509],
       ...,
       [577.55474938],
       [289.1849985 ],
       [377.91824228]])

In [47]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)

In [48]:
mse

42442.785524751795

In [49]:
mse_unsquared = (mse)**0.5

In [50]:
mse_unsquared

206.0164690619461

In [ ]:
#my mean squared error is quite low so the models predictions are close to the actual values

In [ ]:
#make a real vs. predict dataframe

In [51]:
pd.DataFrame(y_pred)[0]

0       358.143847
1       368.518441
2       635.380275
3       260.986391
4       561.538016
           ...    
2723    345.142663
2724    640.772855
2725    577.554749
2726    289.184998
2727    377.918242
Name: 0, Length: 2728, dtype: float64

In [52]:
real_vs_pred = pd.DataFrame({'y_test': y_test['total_claim_amount'], 'y_pred':y_pred[:,0]})

In [54]:
real_vs_pred

y_test      y_pred
1250   340.800000  358.143847
5438   195.153339  368.518441
10156  770.400000  635.380275
3441   336.000000  260.986391
682    561.600000  561.538016
...           ...         ...
5063   345.600000  345.142663
10053  664.280864  640.772855
3453   684.000000  577.554749
9241    25.713622  289.184998
10449  497.684017  377.918242

[2728 rows x 2 columns]

Model Validation

Model Evaluation:
MSE.
RMSE.
MAE.
R2.
Adjusted R2.
Feature Importance.

In [61]:
scaled_data_X_test.shape

(2728, 9)

In [63]:
X_test.shape

(2728, 9)

In [62]:
scaled_data_X_train.shape

(8182, 10)

In [66]:
scaled_data_X_train.columns()

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [64]:
X_train.shape

(8182, 9)

In [59]:
scaled_data_X_test = pd.DataFrame(scaled_data_X_test, columns = X_test.columns)
scaled_data_X_train = pd.DataFrame(scaled_data_X_train, columns = X_train.columns)

ValueError: Shape of passed values is (8182, 10), indices imply (8182, 9)

In [38]:
scaled_data_X_test

unnamed:_0  customer_lifetime_value    income  monthly_premium_auto  \
0      -1.335211                -0.760433 -0.356162             -0.643727   
1      -0.000174                -0.790735 -0.560557             -0.643727   
2       1.503815                -0.073986 -1.239629              0.400008   
3      -0.636771                 1.261077  0.403474             -0.672720   
4      -1.516277                 0.183538 -0.006667              0.689934   
...          ...                      ...       ...                   ...   
2723   -0.119715                 1.298055 -0.220130             -0.614734   
2724    1.470981                -0.426642 -0.280149              0.979860   
2725   -0.632946                -0.181434 -1.239629              0.052096   
2726    1.212134                -0.593347  1.812075              0.197059   
2727    1.597217                 0.050921  1.186063              0.313030   

      months_since_last_claim  months_since_policy_inception  \
0                   -1.134555                      -0.251793   
1                   -0.007711                       1.179825   
2                   -0.929675                       0.535597   
3                   -0.110151                      -0.752859   
4                    1.528896                      -0.967602   
...                       ...                            ...   
2723                -1.441877                      -1.504458   
2724                -1.339436                       1.144034   
2725                -0.007711                      -1.432878   
2726                -1.441877                       0.249273   
2727                 1.631336                      -1.576039   

      number_of_open_complaints  number_of_policies     month  
0                     -0.429234           -0.832927  1.062836  
1                      0.707991           -0.832927  1.062836  
2                     -0.429234            2.080537 -0.940879  
3                      2.982439           -0.416718  1.062836  
4                     -0.429234            0.831910  1.062836  
...                         ...                 ...       ...  
2723                   1.845215           -0.416718 -0.940879  
2724                  -0.429234           -0.832927 -0.940879  
2725                  -0.429234            0.831910  1.062836  
2726                  -0.429234           -0.832927  1.062836  
2727                  -0.429234            2.496746  1.062836  

[2728 rows x 9 columns]

In [39]:
scaled_data_X_train

unnamed:_0  customer_lifetime_value    income  monthly_premium_auto  \
0       1.056252                -0.298649  0.352458             -0.556749   
1      -0.926858                -0.392857 -1.239629             -0.556749   
2       1.016087                -0.821583 -0.504792             -0.817683   
3       1.293422                 2.879646 -1.239629              0.544971   
4      -0.463357                 1.002198  1.985075             -0.585742   
...          ...                      ...       ...                   ...   
8177   -1.622111                -0.809832  0.340586             -0.904661   
8178   -1.708499                 0.201285  1.266199              0.631949   
8179    0.828965                -0.455121  0.985263             -0.933653   
8180    0.477354                 1.953516 -1.239629              0.429000   
8181    0.064219                -0.501884 -1.239629             -0.817683   

      months_since_last_claim  months_since_policy_inception  \
0                    0.007560                      -1.468668   
1                    0.402051                       0.821920   
2                    0.094730                       1.609310   
3                    0.811813                      -1.003392   
4                    2.041098                      -0.430745   
...                       ...                            ...   
8177                -1.339436                       0.106112   
8178                -0.417472                      -0.144422   
8179                -1.134555                      -0.931811   
8180                -0.007711                      -1.110764   
8181                 0.914253                       1.609310   

      number_of_open_complaints  number_of_policies     month  
0                      0.007752            0.415700 -0.940879  
1                     -0.429234           -0.000509 -0.940879  
2                     -0.429234           -0.832927 -0.940879  
3                     -0.429234           -0.416718  1.062836  
4                     -0.429234           -0.416718  1.062836  
...                         ...                 ...       ...  
8177                  -0.429234           -0.832927  1.062836  
8178                  -0.429234           -0.000509  1.062836  
8179                  -0.429234            2.496746  1.062836  
8180                  -0.429234           -0.416718 -0.940879  
8181                  -0.429234            2.496746  1.062836  

[8182 rows x 9 columns]

In [41]:
scaled_data_X_train.shape

(8182, 9)

In [42]:
scaled_data_X_test.shape

(2728, 9)

In [44]:
y_train.shape

(8182, 1)

In [45]:
y_test.shape

(2728, 1)

In [31]:
import statsmodels.api as sm
import numpy as np

In [43]:
scaled_data_X_train = sm.add_constant(scaled_data_X_train.to_numpy())

model_1 = sm.OLS(y_train, scaled_data_X_train).fit()
predictions_train = model.predict(scaled_data_X_train)

scaled_data_X_test = sm.add_constant(scaled_data_X_test)
y_pred = model.predict(scaled_data_X_test)
print_model_1 = model_1.summary()
print_model_1

ValueError: X has 10 features, but LinearRegression is expecting 9 features as input.